title: Chimp-4 Engine Ratings
description: Tracking the evolution and strength of the Chimp chess engine.
theme: jekyll-theme-midnight

baseurl: "/chimp-4"
# url: "https://quackcoast.github.io"

# This line helps the theme generate the "View the Project on GitHub" link correctly
# Make sure 'quackcoast' is your GitHub username and 'chimp-4' (or whatever your repo is called) is the repository name
# github:
#  repository_url: https://github.com/quackcoast/chimp-4 # Or your actual repo URL
#  owner_name: quackcoast # Optional, but can help some themes
#  repository_name: chimp-4 # Optional, but can help some themes

# Optional: If you want the "maintained by" link at the bottom to point to your profile
author:
  name: quackcoast
  github: quackcoast

collections:
  engines:
    output: true # <<< MUST BE TRUE
    permalink: /:name.html # This aims for /chimp-4/engine-name.html
